import type {
  Appointment,
  BillingQualification,
  LabResult,
  MessageThread,
  NotificationItem,
  Patient,
  TaskItem,
} from './types';

export const patients: Patient[] = [
  {
    id: '1',
    name: 'John Doe',
    dob: '1955-05-12',
    gender: 'Male',
    riskScore: 85,
    riskLevel: 'HIGH',
    programs: ['CCM', 'RPM'],
    conditions: ['CHF', 'Type 2 Diabetes', 'Hypertension'],
    lastVisit: '2024-02-10',
    nextAppointment: '2024-02-25T10:00:00Z',
    rpmAlerts: 2,
    predictedHospitalization: 45,
    medicationAdherence: 72,
  },
  {
    id: '2',
    name: 'Jane Smith',
    dob: '1962-11-28',
    gender: 'Female',
    riskScore: 42,
    riskLevel: 'MEDIUM',
    programs: ['CCM', 'BHI'],
    conditions: ['Depression', 'COPD'],
    lastVisit: '2024-02-15',
    nextAppointment: '2024-02-26T14:30:00Z',
    predictedHospitalization: 15,
    medicationAdherence: 95,
  },
  {
    id: '3',
    name: 'Robert Wilson',
    dob: '1948-03-05',
    gender: 'Male',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    programs: ['RPM', 'RTM'],
    conditions: ['Chronic Pain', 'Post-Op Recovery', 'AFib'],
    lastVisit: '2024-02-20',
    rpmAlerts: 5,
    predictedHospitalization: 78,
    medicationAdherence: 60,
  },
  {
    id: '4',
    name: 'Mary Johnson',
    dob: '1970-07-15',
    gender: 'Female',
    riskScore: 25,
    riskLevel: 'LOW',
    programs: ['APCM'],
    conditions: ['Pre-diabetes'],
    lastVisit: '2024-01-20',
    predictedHospitalization: 5,
    medicationAdherence: 98,
  },
];

export const appointments: Appointment[] = [
  {
    id: 'a1',
    patientId: '1',
    patientName: 'John Doe',
    startTime: '2024-02-25T10:00:00Z',
    endTime: '2024-02-25T10:30:00Z',
    type: 'Telehealth',
    status: 'Ready',
  },
  {
    id: 'a2',
    patientId: '2',
    patientName: 'Jane Smith',
    startTime: '2024-02-26T14:30:00Z',
    endTime: '2024-02-26T15:00:00Z',
    type: 'In-Person',
    status: 'Scheduled',
  },
  {
    id: 'a3',
    patientId: '3',
    patientName: 'Robert Wilson',
    startTime: '2024-02-26T16:00:00Z',
    endTime: '2024-02-26T16:30:00Z',
    type: 'Telehealth',
    status: 'Scheduled',
  },
];

export const tasks: TaskItem[] = [
  {
    id: 't1',
    title: 'Review John Doe lab results',
    description: 'Electrolyte imbalance detected in recent labs. Correlate with RPM data.',
    patientName: 'John Doe',
    assignedTo: 'Dr. Richardson',
    dueDate: '2024-02-26',
    priority: 'High',
    status: 'Pending',
    category: 'Clinical',
  },
  {
    id: 't2',
    title: 'Call Jane Smith for RPM onboarding',
    description: 'Patient received device but has not activated it yet.',
    patientName: 'Jane Smith',
    assignedTo: 'Nurse Kelly',
    dueDate: '2024-02-27',
    priority: 'Medium',
    status: 'In Progress',
    category: 'Follow-up',
  },
  {
    id: 't3',
    title: 'Finalize CCM documentation',
    description: 'Need 2 more minutes of staff time to qualify for 99490.',
    patientName: 'Robert Wilson',
    assignedTo: 'Dr. Richardson',
    dueDate: '2024-02-25',
    priority: 'High',
    status: 'Completed',
    category: 'Billing',
  },
];

export const billingQualifications: BillingQualification[] = [
  {
    id: 'q1',
    patientId: '1',
    patientName: 'John Doe',
    program: 'RPM',
    code: '99454',
    description: 'RPM device supply and readings',
    status: 'Qualified',
    progress: 100,
  },
  {
    id: 'q2',
    patientId: '1',
    patientName: 'John Doe',
    program: 'RPM',
    code: '99457',
    description: 'RPM interactive communication (20m)',
    status: 'In Progress',
    progress: 75,
  },
  {
    id: 'q3',
    patientId: '2',
    patientName: 'Jane Smith',
    program: 'CCM',
    code: '99490',
    description: 'CCM clinical staff time (20m)',
    status: 'In Progress',
    progress: 40,
  },
  {
    id: 'q4',
    patientId: '3',
    patientName: 'Robert Wilson',
    program: 'RTM',
    code: '98980',
    description: 'RTM treatment management (20m)',
    status: 'Qualified',
    progress: 100,
  },
];

export const labResults: LabResult[] = [
  {
    id: 'l1',
    patientId: '1',
    testName: 'HbA1c',
    date: '2024-02-10',
    value: '7.2%',
    status: 'Abnormal',
  },
  {
    id: 'l2',
    patientId: '1',
    testName: 'eGFR',
    date: '2024-02-10',
    value: '85 mL/min',
    status: 'Normal',
  },
  {
    id: 'l3',
    patientId: '3',
    testName: 'LDL',
    date: '2024-01-15',
    value: '142 mg/dL',
    status: 'Abnormal',
  },
];

export const messages: MessageThread[] = [
  {
    id: 'm1',
    patientName: 'John Doe',
    lastMessage: 'Weight up 3 lbs since yesterday. Please review.',
    timestamp: '2m ago',
    unread: 2,
  },
  {
    id: 'm2',
    patientName: 'Jane Smith',
    lastMessage: 'I have activated my RPM tablet.',
    timestamp: '18m ago',
    unread: 0,
  },
  {
    id: 'm3',
    patientName: 'Robert Wilson',
    lastMessage: 'Pain score still elevated after PT.',
    timestamp: '1h ago',
    unread: 1,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Critical RPM alert',
    body: 'Robert Wilson has 5 new RPM alerts and likely needs same-day review.',
    tone: 'critical',
    time: 'Now',
  },
  {
    id: 'n2',
    title: 'Billing opportunity',
    body: '12 CCM patients are within 2 minutes of 99490 qualification.',
    tone: 'warning',
    time: '12m',
  },
  {
    id: 'n3',
    title: 'Schedule reminder',
    body: 'John Doe telehealth visit begins at 10:00 AM.',
    tone: 'info',
    time: '30m',
  },
];
