import { Patient, PatientRisk, CMSProgram, Appointment } from './types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: '1',
    name: 'John Doe',
    dob: '1955-05-12',
    gender: 'Male',
    riskScore: 85,
    riskLevel: PatientRisk.HIGH,
    programs: [CMSProgram.CCM, CMSProgram.RPM],
    conditions: ['CHF', 'Type 2 Diabetes', 'Hypertension'],
    lastVisit: '2024-02-10',
    nextAppointment: '2024-02-25T10:00:00Z',
    rpmAlerts: 2,
    predictedHospitalization: 45,
    medicationAdherence: 72,
  },
  {
    id: '2',
    name: 'Jane Smith',
    dob: '1962-11-28',
    gender: 'Female',
    riskScore: 42,
    riskLevel: PatientRisk.MEDIUM,
    programs: [CMSProgram.CCM, CMSProgram.BHI],
    conditions: ['Depression', 'COPD'],
    lastVisit: '2024-02-15',
    nextAppointment: '2024-02-26T14:30:00Z',
    predictedHospitalization: 15,
    medicationAdherence: 95,
  },
  {
    id: '3',
    name: 'Robert Wilson',
    dob: '1948-03-05',
    gender: 'Male',
    riskScore: 92,
    riskLevel: PatientRisk.CRITICAL,
    programs: [CMSProgram.RPM, CMSProgram.RTM],
    conditions: ['Chronic Pain', 'Post-Op Recovery', 'AFib'],
    lastVisit: '2024-02-20',
    rpmAlerts: 5,
    predictedHospitalization: 78,
    medicationAdherence: 60,
  },
  {
    id: '4',
    name: 'Mary Johnson',
    dob: '1970-07-15',
    gender: 'Female',
    riskScore: 25,
    riskLevel: PatientRisk.LOW,
    programs: [CMSProgram.APCM],
    conditions: ['Pre-diabetes'],
    lastVisit: '2024-01-20',
    predictedHospitalization: 5,
    medicationAdherence: 98,
  }
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    patientId: '1',
    patientName: 'John Doe',
    startTime: '2024-02-25T10:00:00Z',
    endTime: '2024-02-25T10:30:00Z',
    type: 'Telehealth',
    status: 'Scheduled',
  },
  {
    id: 'a2',
    patientId: '2',
    patientName: 'Jane Smith',
    startTime: '2024-02-26T14:30:00Z',
    endTime: '2024-02-26T15:00:00Z',
    type: 'Telehealth',
    status: 'Scheduled',
  }
];
